defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  # one PR label to rule them all
  - name: Backport patches to all release/* branches
    conditions:
      - base=master
      - label=backport/all
    actions:
      backport:
        branches:
          - release/v0.17.x
          - release/v0.18.x

  - name: Backport patches to the release/v0.17.x branch
    conditions:
      - base=master
      - label=backport/v0.17.x
    actions:
      backport:
        branches:
          - release/v0.17.x

  - name: Backport patches to the release/v0.18.x branch
    conditions:
      - base=master
      - label=backport/v0.18.x
    actions:
      backport:
        branches:
          - release/v0.18.x
